inherit_from:
  - .rubocop_todo.yml
plugins:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-minitest

Migration/DepartmentName:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  Exclude:
    - 'examples/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

RSpec/NoExpectationExample:
  Exclude:
    - 'spec/**/*_spec.rb'
