inherit_from:
  - .rubocop_todo.yml
require: 
  - rubocop-minitest
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5 
  NewCops: disable
  Exclude:
    - 'examples/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
