AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - '.bundle/**/*'
    - '.vscode/**/*'
    - '**/*.gemspec'
    - 'Gemfile'
    - 'spec/**/*'
